=== GeorgOfenbeck/Thesis_Steinmann/tool/sharedEntities/definitions/shared.xsd
<?xml version="1.0" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="classBaseType">
					<xs:attribute name="cBaseType" type="xs:string" use="required" />
					<xs:attribute name="javaBaseType" type="xs:string"
						use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="derivedClass">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="classBaseType">
					<xs:attribute name="baseType" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>


	<xs:complexType name="classBaseType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="field" type="fieldType" />
			<xs:element name="list" type="listType" />
		</xs:choice>

		<xs:attribute name="javaSuffix" type="xs:string" use="optional" />
		<xs:attribute name="cSuffix" type="xs:string" use="optional" />
		<xs:attribute name="isAbstract" type="xs:boolean" use="optional" />
		<xs:attribute name="comment" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="fieldBaseType">
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="comment" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="fieldType">
		<xs:complexContent>
			<xs:extension base="fieldBaseType"></xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="listType">
		<xs:complexContent>
			<xs:extension base="fieldBaseType"></xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== GeorgOfenbeck/Thesis_Steinmann/tool/sharedEntities/definitions/MultiLanguageTestClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<class
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="shared.xsd"
	name="MultiLanguageTestClass" 
	cBaseType="SharedEntityBase"
	javaBaseType=""
	comment="Multi Language Class used for unit tests">
  <field  name="longField" type="long" comment="test field with type 'long'"/>
  <field  name="intField" type="int" comment="test field with type 'int'"/>
  <field  name="boolField" type="bool" comment="test field with type 'bool'"/>
  <field  name="doubleField" type="double" comment="test field with type 'double'"/>
  <field  name="stringField" type="string" comment="test field with type 'string'"/>
  <field  name="ulongField" type="ulong" comment="test field with type 'ulong'"/>
  
  
  <list  name="primitiveList" type="int" comment="list referencing ints"/>
  <list  name="referenceList" type="MultiLanguageTestClass" comment="list referencing full classes"/>
  
  <field name="referenceField" type="MultiLanguageTestClass" comment="field referencing another class"/>
</class>
