=== GeorgOfenbeck/Thesis_Steinmann/tool/multiLanguageClasses/definitions/shared.xsd
<?xml version="1.0" standalone="yes"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"  
	>
        <xs:element name="class">
          <xs:complexType>

          		<xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="field" type="fieldType" />
          			<xs:element name="define" type="defineType"/>
          			<xs:element name="list" type="listType"/>
          		</xs:choice>

          	<xs:attribute name="name" type="xs:string" use="required"/>
          	<xs:attribute name="cBaseType" type="xs:string" use="required" />
          	<xs:attribute name="javaBaseType" type="xs:string" use="required"/>
          	<xs:attribute name="javaSuffix" type="xs:string" use="optional"/>
          	<xs:attribute name="comment" type="xs:string" use="optional"/>
          </xs:complexType>

        </xs:element>
  

        <xs:complexType name="fieldBaseType">
        	<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
        	<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
        	<xs:attribute name="comment" type="xs:string" use="optional"></xs:attribute>
        </xs:complexType>

        <xs:complexType name="fieldType">
        	<xs:complexContent>
        		<xs:extension base="fieldBaseType"></xs:extension>
        	</xs:complexContent>
        </xs:complexType>

        <xs:complexType name="defineType">
        	<xs:complexContent>
        		<xs:extension base="fieldBaseType"></xs:extension>
        	</xs:complexContent>
        </xs:complexType>
        
    <xs:complexType name="listType">
    	<xs:complexContent>
    		<xs:extension base="fieldBaseType"></xs:extension>
    	</xs:complexContent>
    </xs:complexType>
   
</xs:schema>

=== GeorgOfenbeck/Thesis_Steinmann/tool/multiLanguageClasses/definitions/Workload.xml
<?xml version="1.0" encoding="UTF-8"?>
<class
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="shared.xsd"
	name="Workload" 
	cBaseType="MultiLanguageObjectBase"
	javaBaseType="MacroDefinitionContainer"
	javaSuffix="Data"
	comment="A Workload">
	
	<field name="id" type="int" comment="id of the workload"/>
	<field name="kernel" type="KernelBase" comment="kernel to be executed" />
	<field name="measurerSet" type="MeasurerSet" comment="Measurers used to measure from begin to end of the kernel"/>
	<field name="cpu" type="int" comment="CPU the kernel should be started on. -1 means no pinning"/>
	<field name="warmCaches" type="bool" comment="if true, warm caches, if false, clear caches before running the kernel"/>
	
	<list name="waitFor" type="int" comment="ids of the workloads which must be started or killed before this one is started"/>
	<list name="killOnExit" type="int" comment="ids of the workloads to be killed when this workload exits"/>
</class>

=== GeorgOfenbeck/Thesis_Steinmann/tool/multiLanguageClasses/definitions/MultiLanguageTestClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<class
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="shared.xsd"
	name="MultiLanguageTestClass" 
	cBaseType="MultiLanguageObjectBase"
	javaBaseType=""
	comment="Multi Language Class used for unit tests">
  <field  name="longField" type="long" comment="test field with type 'long'"/>
  <field  name="intField" type="int" comment="test field with type 'int'"/>
  <field  name="boolField" type="bool" comment="test field with type 'bool'"/>
  <field  name="doubleField" type="double" comment="test field with type 'double'"/>
  <field  name="stringField" type="string" comment="test field with type 'string'"/>
  
  <list  name="primitiveList" type="int" comment="list referencing ints"/>
  <list  name="referenceList" type="MultiLanguageTestClass" comment="list referencing full classes"/>
  
  <field name="referenceField" type="MultiLanguageTestClass" comment="field referencing another class"/>
</class>
